main : main.o
	gcc -o main main.o 
main.o : main.c
	gcc -std=c99 -Wall -Werror -pedantic -c main.c

test:
	./main <test1
	./main <test2
	./main <test3
	./main <test4
	./main <test5
	./main <test6
gov:
	
int current_element = 0;
int element_before = 0;
int max_length_of_identical = 1;
int temp_max_length_of_identical = 1;

Если пользователь ввел число (current_element)
    element_before = current_element;
Иначе
    return -1

ПОКА пользователь вводит число (current_element)
    Если сurrent_element == element_before
        temp_max_length_of_identical++
    Иначе
        temp_max_length_of_identical = 1

    Если temp_max_length_of_identical > max_length_of_identical
        max_length_of_identical = temp_max_length_of_identical
    
    element_before = current_element;
return 0
